### PR TITLE
finished uptil positioning

### PR DESCRIPTION
**Pull request by wajahat414**
cloneed new york times web page
Learnings
Html semantics
floating elements
Positioning using flex box

### CODE REVIEW

**Review by voscarmv — CHANGES_REQUESTED** [review]
# Impressive work. 💻 👀 ✨ 
- The page looks very similar to the original. Good work there.

## However, there are some changes required 👀 🧰 🔨 🔧 
- Please write a proper README title and description. Also, please add a screenshot of the webpage.
- Please add a proper description on your Pull Request. Make a list of all the new things you learned building this project.
- Please add `node_modules` to your `.gitignore` file and remove it from your repo.
### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

**Comment by wajahat414** [comment]
Done all the changes requested with the best of my knowledge. THanks you

**Review by smcommits — APPROVED** [review]
# Status: Approved :+1:
@wajahat414  Great Job! I can see that you have implemented all the changes requested by the previous TSE. 

This project is approved. You can go ahead and merge the branch. Congratulation and good luck with your next project. 

## Optional 

- [ ]  You have empty "href" attributes in your HTML. It is a general practice to use "#" as a placeholder instead. 

# 
Any further questions? Please reach out to me on [slack](https://microverse-students.slack.com/team/U017N7LLZ40)

**Comment by wajahat414** [comment]
Can I merge it to main branch now??

**Comment by smcommits** [comment]
@wajahat414 Yes! You can go ahead and merge the branch. I am sorry, I should have mentioned that in my previous review. Good Luck! Also, you can submit the project using your dashboard.

**Pull request merged**
